on: [push, pull_request]
name: Code formatting check
jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        project:
          - wii-ext
          - examples/classic-async-embassy-rp
          - examples/classic-blocking-rp2040-hal
          - examples/nunchuk-async-embassy-rp
          - examples/nunchuk-blocking-rp2040-hal
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
          components: rustfmt
      - run: cargo fmt -- --check
